# Generated by Django 5.1.4 on 2025-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fahdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
