# Generated by Django 5.1.4 on 2025-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fahdapp', '0002_alter_reservation_id_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
